config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'rooms#index'
  resources :rooms do
    resources :messages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  validates :content, presence: true

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, :set_room, only: %i[ new create]

  def new
    @message = @room.messages.new
  end


  def create
    @message = @room.messages.new(messages_params)
    # byebug


    mine = ApplicationController.render(
      partial: 'messages/mine', 
      locals: { message: @message } 
    )

    theirs = ApplicationController.render(
      partial: 'messages/theirs', 
      locals: { message: @message } 
    )

    if @message.save
      ActionCable.server.broadcast "room_channel_#{@message.room_id}", mine: mine, theirs: theirs, message: @message
      # redirect_to @room
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def messages_params
    params.require(:message).permit(:content, :room_id).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(rooms_params)
    if @room.save
      redirect_to root_path
    end
  end

  def show
    # redirect_to :back
    # redirect_to :back
    # if @room
    #   respond_to do |format|
    #     format.js {render inline: "location.reload();" }
    #   end
    # end
    # redirect_back(fallback_location: @room.id)
    # redirect_to @room
    # @rooms = Room.all
    # render 'index'
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def rooms_params
    params.require(:room).permit(:name).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatRoomDeviseV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container mt-5">
      <%= yield %>
    </div>

  </body>

</html>

app/views/messages/_message.html.erb
<div class="message <%= 'me' if message.author == current_user %>"  >
  <div class="content-container ">
    <p class='content m-0' >
      <%= message.content %>
    </p>
    <div class='author'>
      <%= message.author.email %>
    </div>
  </div>
</div>

app/views/messages/_mine.html.erb
<div class="message mb-3 me">
  <div class="content-container">
    <div class="content  ">
      <%= message.content %> 
    </div>
    <div class="author">
      <%= message.user.email %> 
    </div>
  </div>
</div>

app/views/messages/_theirs.html.erb
<div class="message mb-3">
  <div class="content-container">
    <div class="content  ">
      <%= message.content %> 
    </div>
    <div class="author">
      <%= message.user.email %> 
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<%= turbo_frame_tag 'new_message', target: '_top' do %>
  <%= form_with(model: [ @message.room, @message ], remote: true) do |form| %>

    <div class="field">
      <%= form.text_field :content %>
      <%= form.submit 'Send', id: 'submit' %>
    </div>

  <% end %>
<% end %>

<%= link_to 'Back', @message.room %>

app/views/rooms/_form.html.erb
<%= form_with model: room, url: rooms_path, method: :post do |form| %>
  <%= form.text_field :name, class: 'form-control' %>
  <%= form.submit 'New Room', class: 'btn btn-primary mt-2' %>
<% end %>

app/views/rooms/index.html.erb
<h1>Rooms</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-3">
      <div>
        <%= render 'form', room: Room.new%>
      </div>
      <div class='mt-3'>
     <% @rooms.each do |room| %>
        <div class="card" >
          <div class="card-body" > 
            
            <%= link_to room.name , room, data: { turbolinks: false }, class: 'room' %>

          </div>
        </div>
    <% end %>
      </div>
    </div>

  </div>
</div>

app/views/rooms/show.html.erb
<div id="user-id" data-user-id="<%= current_user.id  %>"></div>
<div id="room-id" data-room-id="<%= @room.try(:id)  %>"></div>
<h1>
  <%= @room.name %>
</h1>

<div class='chat-msg' id="messages">
  <%= render @room.messages %>
</div>

<%= turbo_frame_tag 'new_message', src: new_room_message_path(@room), target:'_top' %>


<%= link_to 'back', root_path %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <div class="collapse navbar-collapse">
      <ul class='navbar-nav me-auto mb-2 mb-lg-0'>
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, form: { 'data-turbo': 'false' }, class: 'btn btn-danger' %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
          </li>
          
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>

</nav>